<?=date("F j, Y, g:i a")?><br>
<?=date("m.d.y")?><br>
<?=date("j, n, Y")?><br>
<?=date("Ymd")?><br>
<?=date('h-i-s, j-m-y, it is w Day')?><br>
<?=date('\i\t \i\s \t\h\e jS \d\a\y.')?><br>
<?=date("D M j G:i:s T Y")?><br>
<?=date('H:m:s \m \i\s\ \m\o\n\t\h')?><br>
<?=date("H:i:s")?><br>
<?=date("Y-m-d H:i:s")?><br>
